jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: Frontend/farmer
      run: npm install

    - name: Run tests
      working-directory: Frontend/farmer
      run: npm test

    - name: Build frontend
      working-directory: Frontend/farmer
      run: npm run build
