name: Farmer Frontend CI/CD

on:
  push:
    branches:
      - farmer-frontend
    paths:
      - 'Frontend/farmer/**'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: Frontend/farmer
      run: npm install

    - name: Run tests (optional)
      working-directory: Frontend/farmer
      run: npm test || echo "Tests failed or skipped"

    - name: Build project
      working-directory: Frontend/farmer
      run: npm run build

    - name: Deploy via SSH to GCP VM
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_HOST: 35.226.139.217
        REMOTE_PATH: /var/www/farmer-frontend  # adjust to your server directory
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no" Frontend/farmer/build/ $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH
