name: Farmer Frontend CI/CD

on:
  push:
    branches:
      - farmer-frontend
    paths:
      - 'Frontend/farmer/**'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: Frontend/farmer
        run: npm install

      - name: Build frontend
        working-directory: Frontend/farmer
        run: npm run build

      - name: Deploy via SSH
        if: success()
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" Frontend/farmer/dist/ $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH
